// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPEPjUXT85DunOcKv6L9kxtobzp5MV9bc',
    appId: '1:122668418549:web:1713308ffaf145bcf94cbc',
    messagingSenderId: '122668418549',
    projectId: 'auth-test-1907',
    authDomain: 'auth-test-1907.firebaseapp.com',
    storageBucket: 'auth-test-1907.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZrEOMNsg1hHXBmBY2oIZ0TeuA9MkhivM',
    appId: '1:122668418549:android:27ee4a5984a54308f94cbc',
    messagingSenderId: '122668418549',
    projectId: 'auth-test-1907',
    storageBucket: 'auth-test-1907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6kT4CmGt9e3owbntrGwf22Tk0fCOV56o',
    appId: '1:122668418549:ios:acc0079400781980f94cbc',
    messagingSenderId: '122668418549',
    projectId: 'auth-test-1907',
    storageBucket: 'auth-test-1907.appspot.com',
    iosBundleId: 'com.example.authtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6kT4CmGt9e3owbntrGwf22Tk0fCOV56o',
    appId: '1:122668418549:ios:acc0079400781980f94cbc',
    messagingSenderId: '122668418549',
    projectId: 'auth-test-1907',
    storageBucket: 'auth-test-1907.appspot.com',
    iosBundleId: 'com.example.authtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPEPjUXT85DunOcKv6L9kxtobzp5MV9bc',
    appId: '1:122668418549:web:265427052aef6f86f94cbc',
    messagingSenderId: '122668418549',
    projectId: 'auth-test-1907',
    authDomain: 'auth-test-1907.firebaseapp.com',
    storageBucket: 'auth-test-1907.appspot.com',
  );
}
